### ISSUE TITLE
Checklist for AAS239

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-workshop#198]
Pre workshop
==========
- [x] Identify Facilitators
- [x] Submit workshops proposal - Kelle
- [x] Submit catering order - Kelle
- [x] Make new branch in repo
- [x] Decide on topics and additional facilitators
- [x] Order new trainer t-shirts, if needed. - Kelle
- [x] Update readme with dates, times, names
- [x] Check issue tracker for needed updates
- [ ] Update the install instructions
- [x] Add better Windows instructions #175 
- [ ] Set the version of astropy and downstream packages
- [ ] Check materials that they still run
- [ ] Circulate pre-req materials to registrants. 
        Emails in 00_Install and Setup folder.
        Send setup instructions at least 2 weeks before workshop
- [ ] Make Pre and post Surveys .
- [ ] Setup Binder
- [x] Trainers should refresh their teaching skills with this Carpentries lesson: [Live Coding is a Skill](https://carpentries.github.io/instructor-training/17-live/index.html)

Supplies Needed
==========
- [ ] Red/green stickies

During workshop
==========

- [ ] Provide survey link during last coffee break. Don’t wait until the end when people are tired and hungry.

After workshop
==========
- [ ] Make summary report of survey results. Post to relevant issue.

**Comment by stargaser** [comment]
Closing this issue as AAS 239 was canceled. The checklist is a good template for future workshops.
