### ISSUE TITLE
Vet AAS235 notebooks by 2019-12-06

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-workshop#90]
Pre-requisite for #65 and #80. Check the box(es) when the notebook(s) assigned to you works as intended and report back estimated time needed **for participants**. You are free to test other's notebooks if you wish but only the assigned instructor should sign off.

* Do your materials work with the environment in the installation instructions? What OS and `conda` versions? Anaconda or Miniconda?
* How long does it take for you to work through the materials, keeping in mind that you will likely go 2x to 3x faster than a workshop participant?

Assignments:

- [x] @pllim -- Astropy Units, Quantities, and Constants, see also #97 and #99 (**30-min slot might not be enough**)
- [x] @adrn -- Coordinates, see also #83 and #84 (**Need to be extended to 60 mins**)
- [x] @pllim -- I/O: FITS and ASCII, see also #101 (**30-min slot okay**)
- [ ] @bsipocz -- Astropy Tables, see also #77 (**Tentative: Remains 30 mins unless TimeSeries is added**)
- [x] @stargaser -- WCS and Images, see also #102 (**30-min slot okay**)
- [x] @shannnnnyyy -- Photutils, see also #92 (**40 mins without exercises**)
- [x] @eteq -- Specutils, see also #88 and #89  (**Can cut down to 30-45 min**, compat with astropy 4.0 is out of scope for this issue)

Notes:

* @pllim used Miniconda on Windows 10.

**Comment by stargaser** [comment]
For 08-WCS:

- Notebooks executed, with the astropy-workshop environment, without any problems.
- Working through WCS took 16 minutes
    - 3 min slides
    - 2 min execute and talk through notebook explanatory parts
    - 11 min for me to complete the (not fun, see #13) exercises.
- Working through visualization took me 7 minutes
   - 3 min to execute and talk through notebook explanatory parts
   - 4 minutes for me to complete the exercises
23 minutes total for me.

**Comment by pllim** [comment]
> 23 minutes total for me

Assuming students would take longer and the slot is 30 mins, do you think you need a longer slot for that section, @stargaser ?

**Comment by stargaser** [comment]
At this time, I think I would prefer to keep to 30 minutes and restructure the WCS exercises, and maybe even the explanatory parts about SIP and TPV distortions which most users probably do not care about. My guess is that participants probably want less of the details. Other opinions welcome!

**Comment by pllim** [comment]
@stargaser , sounds good to me! You can always move the stuff you are not covering to the bottom under a section that says something like "advanced topics we not covering but you can read up on your own."

**Comment by pllim** [comment]
"Astropy Units, Quantities, and Constants" ran to completion without a problem, except a Windows specific thingy that is explained by #97. I suggested changes to this module at #99 as a follow-up.

**Comment by pllim** [comment]
"I/O: FITS and ASCII" also ran to completion without a problem. I suggested changes to this module at #101 as a follow-up.

**Comment by eteq** [comment]
I think 30-45 min is ok for specutils, although the 2-notebook nature of it means it's a bit flexible if we need to adjust things.

**Comment by adrn** [comment]
I would book 1 hour for coordinates, but I'm pretty flexible and can compress or expand from there. I'm fine with not getting through every cell or every exercise in the notebook, and I've found that timing often has to be gauged on-the-fly (and not based on my experience running through the notebook!).

**Comment by bsipocz** [comment]
I haven't tested and timed the  table notebook, and don't think will have time this week.

**Comment by eteq** [comment]
@bsipocz - ok - over in #65 we'll leave it as-is, but if you manage to get #77 in we can add 15 min for that and take that from specutils or photutils

**Comment by shannnnnyyy** [comment]
the photutils notebook took me about 40 mins before the exercise to get through. This will be modulated with public speaking nerves, but I'm not sure in which direction that will be...

**Comment by pllim** [comment]
@eteq , I summarized the timing back in the original issue above. If you have enough information to proceed with updating the schedule, please close this issue.

**Comment by eteq** [comment]
I think we have what we need to proceed, so closing as @pllim suggests.  But @bsipocz, if you have the chance please let us know how much time it takes since we can adjust the schedule a bit if need be.
